# Generated by Django 3.2.7 on 2021-09-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('reference', models.CharField(max_length=100, verbose_name='reference')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price')),
                ('ean13', models.CharField(blank=True, default='', max_length=13, verbose_name='ean13')),
                ('ean13_gen', models.CharField(blank=True, default='', max_length=13, verbose_name='ean13_gen')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
            ],
        ),
    ]
