# Generated by Django 3.2.7 on 2021-09-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20210918_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean13',
            field=models.TextField(blank=True, default='', verbose_name='ean13'),
        ),
    ]
