# Generated by Django 3.2.7 on 2021-09-23 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_alter_product_ean13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.CharField(default='-', max_length=100, verbose_name='customer_email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='-', max_length=100, verbose_name='customer_name'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='pos.product'),
        ),
    ]
